"""
core/archetypes/taxonomy.py

Predefined job-role taxonomy used by the bootstrapper to build archetype centroids.
Each entry has a unique title and the category it belongs to.

Duplicates across categories are intentionally deduplicated — first occurrence wins.
Run  python -m core.archetypes.bootstrapper  to upsert these into role_archetypes.
"""

ARCHETYPES: list[dict] = [
    # ── 1. Software Engineering & IT Infrastructure ───────────────────────────
    {"title": "Junior Software Engineer",        "category": "Software Engineering & IT Infrastructure"},
    {"title": "Software Engineer",               "category": "Software Engineering & IT Infrastructure"},
    {"title": "Junior Backend Engineer",         "category": "Software Engineering & IT Infrastructure"},
    {"title": "Backend Engineer",                "category": "Software Engineering & IT Infrastructure"},
    {"title": "Junior Frontend Engineer",        "category": "Software Engineering & IT Infrastructure"},
    {"title": "Frontend Engineer",               "category": "Software Engineering & IT Infrastructure"},
    {"title": "Junior Full Stack Engineer",      "category": "Software Engineering & IT Infrastructure"},
    {"title": "Full Stack Engineer",             "category": "Software Engineering & IT Infrastructure"},
    {"title": "Junior QA Engineer",              "category": "Software Engineering & IT Infrastructure"},
    {"title": "QA Engineer",                     "category": "Software Engineering & IT Infrastructure"},
    {"title": "Test Automation Engineer",        "category": "Software Engineering & IT Infrastructure"},
    {"title": "Senior Software Engineer",        "category": "Software Engineering & IT Infrastructure"},
    {"title": "Senior Backend Engineer",         "category": "Software Engineering & IT Infrastructure"},
    {"title": "Senior Frontend Engineer",        "category": "Software Engineering & IT Infrastructure"},
    {"title": "Senior Full Stack Engineer",      "category": "Software Engineering & IT Infrastructure"},
    {"title": "Staff Engineer",                  "category": "Software Engineering & IT Infrastructure"},
    {"title": "Senior Staff Engineer",           "category": "Software Engineering & IT Infrastructure"},
    {"title": "Principal Engineer",              "category": "Software Engineering & IT Infrastructure"},
    {"title": "Distinguished Engineer",          "category": "Software Engineering & IT Infrastructure"},
    {"title": "Senior QA Engineer",              "category": "Software Engineering & IT Infrastructure"},
    {"title": "Senior Test Automation Engineer", "category": "Software Engineering & IT Infrastructure"},
    {"title": "Founding Engineer",               "category": "Software Engineering & IT Infrastructure"},
    {"title": "Founding Full Stack Engineer",    "category": "Software Engineering & IT Infrastructure"},
    {"title": "Founding Backend Engineer",       "category": "Software Engineering & IT Infrastructure"},
    {"title": "Technical Co-Founder",            "category": "Software Engineering & IT Infrastructure"},
    {"title": "DevOps Engineer",                 "category": "Software Engineering & IT Infrastructure"},
    {"title": "Senior DevOps Engineer",          "category": "Software Engineering & IT Infrastructure"},
    {"title": "Site Reliability Engineer (SRE)", "category": "Software Engineering & IT Infrastructure"},
    {"title": "Senior SRE",                      "category": "Software Engineering & IT Infrastructure"},
    {"title": "Cloud Engineer",                  "category": "Software Engineering & IT Infrastructure"},
    {"title": "Senior Cloud Engineer",           "category": "Software Engineering & IT Infrastructure"},
    {"title": "Platform Engineer",               "category": "Software Engineering & IT Infrastructure"},
    {"title": "Senior Platform Engineer",        "category": "Software Engineering & IT Infrastructure"},
    {"title": "Cloud Architect",                 "category": "Software Engineering & IT Infrastructure"},
    {"title": "Solutions Architect",             "category": "Software Engineering & IT Infrastructure"},
    {"title": "Security Engineer",               "category": "Software Engineering & IT Infrastructure"},
    {"title": "Senior Security Engineer",        "category": "Software Engineering & IT Infrastructure"},
    {"title": "Cybersecurity Analyst",           "category": "Software Engineering & IT Infrastructure"},
    {"title": "Network Engineer",                "category": "Software Engineering & IT Infrastructure"},
    {"title": "Systems Engineer",                "category": "Software Engineering & IT Infrastructure"},
    {"title": "Senior Systems Engineer",         "category": "Software Engineering & IT Infrastructure"},
    {"title": "IT Support Specialist",           "category": "Software Engineering & IT Infrastructure"},
    {"title": "IT Specialist",                   "category": "Software Engineering & IT Infrastructure"},
    {"title": "IT Manager",                      "category": "Software Engineering & IT Infrastructure"},
    {"title": "IT Service Management Manager",   "category": "Software Engineering & IT Infrastructure"},
    {"title": "ServiceNow Administrator",        "category": "Software Engineering & IT Infrastructure"},
    {"title": "ServiceNow Developer",            "category": "Software Engineering & IT Infrastructure"},
    {"title": "ServiceNow Architect",            "category": "Software Engineering & IT Infrastructure"},
    {"title": "IT Operations Manager",           "category": "Software Engineering & IT Infrastructure"},

    # ── 2. Machine Learning & AI ──────────────────────────────────────────────
    {"title": "Machine Learning Engineer",         "category": "Machine Learning & AI"},
    {"title": "Senior Machine Learning Engineer",  "category": "Machine Learning & AI"},
    {"title": "Applied ML Engineer",               "category": "Machine Learning & AI"},
    {"title": "Senior Applied ML Engineer",        "category": "Machine Learning & AI"},
    {"title": "Deep Learning Engineer",            "category": "Machine Learning & AI"},
    {"title": "Computer Vision Engineer",          "category": "Machine Learning & AI"},
    {"title": "Senior Computer Vision Engineer",   "category": "Machine Learning & AI"},
    {"title": "NLP Engineer",                      "category": "Machine Learning & AI"},
    {"title": "Senior NLP Engineer",               "category": "Machine Learning & AI"},
    {"title": "AI Research Scientist",             "category": "Machine Learning & AI"},
    {"title": "Senior AI Research Scientist",      "category": "Machine Learning & AI"},
    {"title": "ML Research Engineer",              "category": "Machine Learning & AI"},
    {"title": "Research Scientist (ML)",           "category": "Machine Learning & AI"},
    {"title": "AI Product Manager",                "category": "Machine Learning & AI"},
    {"title": "Senior AI Product Manager",         "category": "Machine Learning & AI"},
    {"title": "AI Solutions Architect",            "category": "Machine Learning & AI"},
    {"title": "AI Strategist",                     "category": "Machine Learning & AI"},
    {"title": "Head of AI",                        "category": "Machine Learning & AI"},
    {"title": "Director of AI",                    "category": "Machine Learning & AI"},
    {"title": "VP of AI",                          "category": "Machine Learning & AI"},
    {"title": "Chief AI Officer (CAIO)",           "category": "Machine Learning & AI"},
    {"title": "Prompt Engineer",                   "category": "Machine Learning & AI"},
    {"title": "Senior Prompt Engineer",            "category": "Machine Learning & AI"},
    {"title": "AI Agent Developer",                "category": "Machine Learning & AI"},
    {"title": "AI Automation Specialist",          "category": "Machine Learning & AI"},
    {"title": "AI Content Strategist",             "category": "Machine Learning & AI"},
    {"title": "AI Trainer / Data Annotation Lead", "category": "Machine Learning & AI"},
    {"title": "MLOps Engineer",                    "category": "Machine Learning & AI"},
    {"title": "Senior MLOps Engineer",             "category": "Machine Learning & AI"},
    {"title": "AI Ethics Consultant",              "category": "Machine Learning & AI"},
    {"title": "AI Risk & Compliance Officer",      "category": "Machine Learning & AI"},
    {"title": "Founding ML Engineer",              "category": "Machine Learning & AI"},
    {"title": "Founding AI Engineer",              "category": "Machine Learning & AI"},
    {"title": "GTM AI Engineer",                   "category": "Machine Learning & AI"},
    {"title": "AI GTM Specialist",                 "category": "Machine Learning & AI"},

    # ── 3. Data Science & Analytics ───────────────────────────────────────────
    {"title": "Data Scientist",                      "category": "Data Science & Analytics"},
    {"title": "Senior Data Scientist",               "category": "Data Science & Analytics"},
    {"title": "Principal Data Scientist",            "category": "Data Science & Analytics"},
    {"title": "Staff Data Scientist",                "category": "Data Science & Analytics"},
    {"title": "Lead Data Scientist",                 "category": "Data Science & Analytics"},
    {"title": "Data Analyst",                        "category": "Data Science & Analytics"},
    {"title": "Senior Data Analyst",                 "category": "Data Science & Analytics"},
    {"title": "Analytics Engineer",                  "category": "Data Science & Analytics"},
    {"title": "Senior Analytics Engineer",           "category": "Data Science & Analytics"},
    {"title": "BI Analyst",                          "category": "Data Science & Analytics"},
    {"title": "Senior BI Analyst",                   "category": "Data Science & Analytics"},
    {"title": "Business Intelligence Engineer",      "category": "Data Science & Analytics"},
    {"title": "Senior Business Intelligence Engineer","category": "Data Science & Analytics"},
    {"title": "Sales Analytics Manager",             "category": "Data Science & Analytics"},
    {"title": "Marketing Analytics Manager",         "category": "Data Science & Analytics"},
    {"title": "Data Engineer",                       "category": "Data Science & Analytics"},
    {"title": "Senior Data Engineer",                "category": "Data Science & Analytics"},
    {"title": "Staff Data Engineer",                 "category": "Data Science & Analytics"},
    {"title": "Principal Data Engineer",             "category": "Data Science & Analytics"},
    {"title": "Data Platform Engineer",              "category": "Data Science & Analytics"},
    {"title": "Data Architect",                      "category": "Data Science & Analytics"},
    {"title": "Databricks Solutions Architect",      "category": "Data Science & Analytics"},
    {"title": "Lakehouse Engineer",                  "category": "Data Science & Analytics"},
    {"title": "Head of Data",                        "category": "Data Science & Analytics"},
    {"title": "Director of Data Science",            "category": "Data Science & Analytics"},
    {"title": "Director of Data Engineering",        "category": "Data Science & Analytics"},
    {"title": "VP of Data",                          "category": "Data Science & Analytics"},
    {"title": "Chief Data Officer (CDO)",            "category": "Data Science & Analytics"},

    # ── 4. Product, Design & UX ───────────────────────────────────────────────
    {"title": "Associate Product Manager",     "category": "Product, Design & UX"},
    {"title": "Product Manager",               "category": "Product, Design & UX"},
    {"title": "Senior Product Manager",        "category": "Product, Design & UX"},
    {"title": "Group Product Manager",         "category": "Product, Design & UX"},
    {"title": "Principal Product Manager",     "category": "Product, Design & UX"},
    {"title": "Technical Product Manager",     "category": "Product, Design & UX"},
    {"title": "Senior Technical Product Manager","category": "Product, Design & UX"},
    {"title": "Director of Product",           "category": "Product, Design & UX"},
    {"title": "VP of Product",                 "category": "Product, Design & UX"},
    {"title": "CPO (Chief Product Officer)",   "category": "Product, Design & UX"},
    {"title": "Product Designer",              "category": "Product, Design & UX"},
    {"title": "Senior Product Designer",       "category": "Product, Design & UX"},
    {"title": "Staff Product Designer",        "category": "Product, Design & UX"},
    {"title": "Principal Product Designer",    "category": "Product, Design & UX"},
    {"title": "UX Designer",                   "category": "Product, Design & UX"},
    {"title": "Senior UX Designer",            "category": "Product, Design & UX"},
    {"title": "UI Designer",                   "category": "Product, Design & UX"},
    {"title": "Senior UI Designer",            "category": "Product, Design & UX"},
    {"title": "UX Researcher",                 "category": "Product, Design & UX"},
    {"title": "Senior UX Researcher",          "category": "Product, Design & UX"},
    {"title": "Interaction Designer",          "category": "Product, Design & UX"},
    {"title": "UX Writer",                     "category": "Product, Design & UX"},
    {"title": "Design Lead",                   "category": "Product, Design & UX"},
    {"title": "Creative Content & Production Lead", "category": "Product, Design & UX"},
    {"title": "Head of Design",                "category": "Product, Design & UX"},
    {"title": "Director of Design",            "category": "Product, Design & UX"},

    # ── 5. Sales & Business Development ──────────────────────────────────────
    {"title": "Sales Development Rep (SDR)",          "category": "Sales & Business Development"},
    {"title": "Senior SDR",                            "category": "Sales & Business Development"},
    {"title": "Account Development Rep (ADR)",         "category": "Sales & Business Development"},
    {"title": "Account Executive",                     "category": "Sales & Business Development"},
    {"title": "Senior Account Executive",              "category": "Sales & Business Development"},
    {"title": "Enterprise Account Executive",          "category": "Sales & Business Development"},
    {"title": "Senior Enterprise Account Executive",   "category": "Sales & Business Development"},
    {"title": "Mid-Market Account Executive",          "category": "Sales & Business Development"},
    {"title": "SMB Account Executive",                 "category": "Sales & Business Development"},
    {"title": "Sales Manager",                         "category": "Sales & Business Development"},
    {"title": "Senior Sales Manager",                  "category": "Sales & Business Development"},
    {"title": "Regional Sales Manager",                "category": "Sales & Business Development"},
    {"title": "Director of Sales",                     "category": "Sales & Business Development"},
    {"title": "VP of Sales",                           "category": "Sales & Business Development"},
    {"title": "Chief Revenue Officer (CRO)",           "category": "Sales & Business Development"},
    {"title": "Business Development Manager",          "category": "Sales & Business Development"},
    {"title": "Senior Business Development Manager",   "category": "Sales & Business Development"},
    {"title": "GTM Manager (Go-To-Market)",            "category": "Sales & Business Development"},
    {"title": "GTM Specialist",                        "category": "Sales & Business Development"},
    {"title": "Senior GTM Specialist",                 "category": "Sales & Business Development"},
    {"title": "Digital Sales Specialist",              "category": "Sales & Business Development"},
    {"title": "Customer Success Manager",              "category": "Sales & Business Development"},
    {"title": "Senior Customer Success Manager",       "category": "Sales & Business Development"},
    {"title": "Account Manager",                       "category": "Sales & Business Development"},
    {"title": "Senior Account Manager",                "category": "Sales & Business Development"},

    # ── 6. Marketing & Communications ────────────────────────────────────────
    {"title": "Digital Marketing Specialist",      "category": "Marketing & Communications"},
    {"title": "Senior Digital Marketing Specialist","category": "Marketing & Communications"},
    {"title": "Growth Marketing Manager",          "category": "Marketing & Communications"},
    {"title": "Senior Growth Marketing Manager",   "category": "Marketing & Communications"},
    {"title": "Performance Marketing Manager",     "category": "Marketing & Communications"},
    {"title": "PPC Specialist",                    "category": "Marketing & Communications"},
    {"title": "SEO Specialist",                    "category": "Marketing & Communications"},
    {"title": "Social Media Manager",              "category": "Marketing & Communications"},
    {"title": "Senior Social Media Manager",       "category": "Marketing & Communications"},
    {"title": "Content Marketing Manager",         "category": "Marketing & Communications"},
    {"title": "Senior Content Marketing Manager",  "category": "Marketing & Communications"},
    {"title": "Content Strategist",                "category": "Marketing & Communications"},
    {"title": "Email Marketing Specialist",        "category": "Marketing & Communications"},
    {"title": "Product Marketing Manager",         "category": "Marketing & Communications"},
    {"title": "Senior Product Marketing Manager",  "category": "Marketing & Communications"},
    {"title": "Brand Manager",                     "category": "Marketing & Communications"},
    {"title": "Senior Brand Manager",              "category": "Marketing & Communications"},
    {"title": "Marketing Manager",                 "category": "Marketing & Communications"},
    {"title": "Senior Marketing Manager",          "category": "Marketing & Communications"},
    {"title": "Director of Marketing",             "category": "Marketing & Communications"},
    {"title": "VP of Marketing",                   "category": "Marketing & Communications"},
    {"title": "CMO (Chief Marketing Officer)",     "category": "Marketing & Communications"},
    {"title": "Communications Manager",            "category": "Marketing & Communications"},
    {"title": "Senior Communications Manager",     "category": "Marketing & Communications"},
    {"title": "Public Relations Specialist",       "category": "Marketing & Communications"},
    {"title": "Copywriter",                        "category": "Marketing & Communications"},
    {"title": "Senior Copywriter",                 "category": "Marketing & Communications"},
    {"title": "Creative Director",                 "category": "Marketing & Communications"},

    # ── 7. Human Resources & People Operations ────────────────────────────────
    {"title": "HR Generalist",                    "category": "Human Resources & People Operations"},
    {"title": "Senior HR Generalist",             "category": "Human Resources & People Operations"},
    {"title": "HR Business Partner",              "category": "Human Resources & People Operations"},
    {"title": "Senior HR Business Partner",       "category": "Human Resources & People Operations"},
    {"title": "People Operations Manager",        "category": "Human Resources & People Operations"},
    {"title": "Senior People Operations Manager", "category": "Human Resources & People Operations"},
    {"title": "Recruiter",                        "category": "Human Resources & People Operations"},
    {"title": "Senior Recruiter",                 "category": "Human Resources & People Operations"},
    {"title": "Technical Recruiter",              "category": "Human Resources & People Operations"},
    {"title": "Senior Technical Recruiter",       "category": "Human Resources & People Operations"},
    {"title": "Talent Acquisition Specialist",    "category": "Human Resources & People Operations"},
    {"title": "Senior Talent Acquisition Specialist","category": "Human Resources & People Operations"},
    {"title": "Talent Acquisition Manager",       "category": "Human Resources & People Operations"},
    {"title": "Head of Talent",                   "category": "Human Resources & People Operations"},
    {"title": "Director of Talent Acquisition",   "category": "Human Resources & People Operations"},
    {"title": "HR Manager",                       "category": "Human Resources & People Operations"},
    {"title": "Senior HR Manager",                "category": "Human Resources & People Operations"},
    {"title": "Director of HR",                   "category": "Human Resources & People Operations"},
    {"title": "VP of People",                     "category": "Human Resources & People Operations"},
    {"title": "CHRO (Chief Human Resources Officer)", "category": "Human Resources & People Operations"},
    {"title": "Learning & Development Manager",   "category": "Human Resources & People Operations"},
    {"title": "Senior L&D Manager",               "category": "Human Resources & People Operations"},
    {"title": "Corporate Trainer",                "category": "Human Resources & People Operations"},
    {"title": "Training & Development Specialist","category": "Human Resources & People Operations"},

    # ── 8. Leadership & Executive (Cross-Domain) ──────────────────────────────
    {"title": "CEO",                    "category": "Leadership & Executive"},
    {"title": "COO",                    "category": "Leadership & Executive"},
    {"title": "CFO",                    "category": "Leadership & Executive"},
    {"title": "CTO",                    "category": "Leadership & Executive"},
    {"title": "VP of Engineering",      "category": "Leadership & Executive"},
    {"title": "Director of Engineering","category": "Leadership & Executive"},
    {"title": "Deputy Program Manager", "category": "Leadership & Executive"},
    {"title": "Program Manager",        "category": "Leadership & Executive"},
    {"title": "Senior Program Manager", "category": "Leadership & Executive"},
    {"title": "Project Manager",        "category": "Leadership & Executive"},
    {"title": "Senior Project Manager", "category": "Leadership & Executive"},

    # ── 9. Finance & Accounting ───────────────────────────────────────────────
    {"title": "Financial Analyst",          "category": "Finance & Accounting"},
    {"title": "Senior Financial Analyst",   "category": "Finance & Accounting"},
    {"title": "FP&A Analyst",               "category": "Finance & Accounting"},
    {"title": "Senior FP&A Analyst",        "category": "Finance & Accounting"},
    {"title": "Accounting Manager",         "category": "Finance & Accounting"},
    {"title": "Senior Accounting Manager",  "category": "Finance & Accounting"},
    {"title": "Controller",                 "category": "Finance & Accounting"},
    {"title": "Senior Controller",          "category": "Finance & Accounting"},
    {"title": "Investment Analyst",         "category": "Finance & Accounting"},
    {"title": "Senior Investment Analyst",  "category": "Finance & Accounting"},
    {"title": "Quantitative Analyst (Quant)","category": "Finance & Accounting"},
    {"title": "Risk Analyst",               "category": "Finance & Accounting"},
    {"title": "Treasury Analyst",           "category": "Finance & Accounting"},

    # ── 10. Healthcare & Life Sciences ────────────────────────────────────────
    {"title": "Registered Nurse (RN)",              "category": "Healthcare & Life Sciences"},
    {"title": "Senior RN",                           "category": "Healthcare & Life Sciences"},
    {"title": "Nurse Practitioner",                  "category": "Healthcare & Life Sciences"},
    {"title": "Physician Assistant",                 "category": "Healthcare & Life Sciences"},
    {"title": "Medical Doctor (MD)",                 "category": "Healthcare & Life Sciences"},
    {"title": "Telemedicine Support Specialist",     "category": "Healthcare & Life Sciences"},
    {"title": "Healthcare Administrator",            "category": "Healthcare & Life Sciences"},
    {"title": "Medical Office Administrator",        "category": "Healthcare & Life Sciences"},
    {"title": "Health Services Manager",             "category": "Healthcare & Life Sciences"},
    {"title": "Care Coordinator",                    "category": "Healthcare & Life Sciences"},
    {"title": "Chronic Disease Coordinator",         "category": "Healthcare & Life Sciences"},
    {"title": "Health Data Analyst",                 "category": "Healthcare & Life Sciences"},
    {"title": "Senior Health Data Analyst",          "category": "Healthcare & Life Sciences"},
    {"title": "Biostatistician",                     "category": "Healthcare & Life Sciences"},
    {"title": "Medical Researcher",                  "category": "Healthcare & Life Sciences"},
    {"title": "Clinical Research Coordinator",       "category": "Healthcare & Life Sciences"},
    {"title": "AI-Powered Diagnostics Specialist",   "category": "Healthcare & Life Sciences"},
    {"title": "AI Healthcare Developer",             "category": "Healthcare & Life Sciences"},
    {"title": "Health Informatics Specialist",       "category": "Healthcare & Life Sciences"},
    {"title": "Pharmacist",                          "category": "Healthcare & Life Sciences"},
    {"title": "Physical Therapist",                  "category": "Healthcare & Life Sciences"},
    {"title": "Mental Health Counselor",             "category": "Healthcare & Life Sciences"},

    # ── 11. Teaching & Education ──────────────────────────────────────────────
    {"title": "K-12 Teacher",                        "category": "Teaching & Education"},
    {"title": "High School Teacher",                 "category": "Teaching & Education"},
    {"title": "Special Education Teacher",           "category": "Teaching & Education"},
    {"title": "College Professor",                   "category": "Teaching & Education"},
    {"title": "Lecturer",                            "category": "Teaching & Education"},
    {"title": "Academic Advisor",                    "category": "Teaching & Education"},
    {"title": "Instructional Designer",              "category": "Teaching & Education"},
    {"title": "Senior Instructional Designer",       "category": "Teaching & Education"},
    {"title": "Learning Engineer",                   "category": "Teaching & Education"},
    {"title": "Digital Learning Designer",           "category": "Teaching & Education"},
    {"title": "Learning Strategist",                 "category": "Teaching & Education"},
    {"title": "Education Coordinator",               "category": "Teaching & Education"},
    {"title": "Head of Learning",                    "category": "Teaching & Education"},
    {"title": "Director of Learning & Development",  "category": "Teaching & Education"},

    # ── 12. Arts, Creative & Media ────────────────────────────────────────────
    {"title": "Graphic Designer",       "category": "Arts, Creative & Media"},
    {"title": "Senior Graphic Designer","category": "Arts, Creative & Media"},
    {"title": "Video Editor",           "category": "Arts, Creative & Media"},
    {"title": "Senior Video Editor",    "category": "Arts, Creative & Media"},
    {"title": "Animator",               "category": "Arts, Creative & Media"},
    {"title": "Game Designer",          "category": "Arts, Creative & Media"},
    {"title": "Film Director",          "category": "Arts, Creative & Media"},
    {"title": "Filmmaker",              "category": "Arts, Creative & Media"},
    {"title": "Photographer",           "category": "Arts, Creative & Media"},
    {"title": "Art Director",           "category": "Arts, Creative & Media"},
    {"title": "Art Curator",            "category": "Arts, Creative & Media"},
    {"title": "Music Producer",         "category": "Arts, Creative & Media"},
    {"title": "Singer/Songwriter",      "category": "Arts, Creative & Media"},
    {"title": "Fashion Designer",       "category": "Arts, Creative & Media"},
    {"title": "Writer / Content Creator","category": "Arts, Creative & Media"},
    {"title": "Journalist",             "category": "Arts, Creative & Media"},
    {"title": "Editor",                 "category": "Arts, Creative & Media"},

    # ── 13. Operations, Legal & Admin ─────────────────────────────────────────
    {"title": "Operations Manager",        "category": "Operations, Legal & Admin"},
    {"title": "Senior Operations Manager", "category": "Operations, Legal & Admin"},
    {"title": "Supply Chain Manager",      "category": "Operations, Legal & Admin"},
    {"title": "Logistics Manager",         "category": "Operations, Legal & Admin"},
    {"title": "Office Manager",            "category": "Operations, Legal & Admin"},
    {"title": "Administrative Assistant",  "category": "Operations, Legal & Admin"},
    {"title": "Executive Assistant",       "category": "Operations, Legal & Admin"},
    {"title": "Paralegal",                 "category": "Operations, Legal & Admin"},
    {"title": "Lawyer",                    "category": "Operations, Legal & Admin"},
    {"title": "Legal Counsel",             "category": "Operations, Legal & Admin"},
    {"title": "Compliance Officer",        "category": "Operations, Legal & Admin"},
]

# Deduplicated list (title is the key; first occurrence wins across categories)
_seen: set[str] = set()
_deduped: list[dict] = []
for _a in ARCHETYPES:
    if _a["title"] not in _seen:
        _seen.add(_a["title"])
        _deduped.append(_a)
ARCHETYPES = _deduped
del _seen, _deduped, _a
