"""
core/embeddings/__init__.py

Embedding consistency contract for CareerOS.
Read this before touching job_embedder.py or resume_embedder.py.

WHY THIS FILE EXISTS
─────────────────────
Cosine similarity only produces meaningful fit scores if every vector
in the system was generated by the same model with the same format.
Jobs and resumes must share one vector space — not two separate ones.

THE FOUR RULES (breaking any of these silently corrupts fit scores)
────────────────────────────────────────────────────────────────────

Rule 1 — Single model, always
    Both embedders use MODEL_NAME defined here.
    To upgrade: change MODEL_NAME, then re-run embed_jobs AND
    re-embed every resume. Mixing models = garbage cosine scores.

Rule 2 — Same preprocessing philosophy
    Jobs:    title + company + location → description → skills
    Resumes: role → skills → raw_text
    Highest-signal fields always appear first in the text string.

Rule 3 — Preserve high-signal fields, truncate context
    Jobs:    title / company / location are NEVER removed
    Resumes: role / skills are NEVER removed
    description and raw_text are the first things truncated.

Rule 4 — No LLM in the embedding layer
    Embedding must be deterministic. Same input = same vector, always.
    No classification, no summarisation, no LLM preprocessing.
    The LLM layer lives in normalization and strategy — not here.

CHANGING THE MODEL
───────────────────
    1. Update MODEL_NAME below
    2. Update EMBEDDING_DIMENSIONS to match the new model's output size
    3. Update your schema.sql / Alembic migration:
         ALTER TABLE job_embeddings ALTER COLUMN embedding TYPE vector(NEW_DIM);
         ALTER TABLE resume_embeddings ALTER COLUMN embedding TYPE vector(NEW_DIM);
    4. Re-run: python -m core.embeddings.job_embedder
    5. Re-embed every resume
    6. Re-run clustering (Phase 5) — old centroids are now invalid
"""

# The single source of truth. Both embedder files import from here.
MODEL_NAME           = "all-MiniLM-L6-v2"  # fast local model, no API key
EMBEDDING_DIMENSIONS = 384                  # dimensions for all-MiniLM-L6-v2
MAX_CHARS            = 1000                 # character cap before encoding

__all__ = ["MODEL_NAME", "EMBEDDING_DIMENSIONS", "MAX_CHARS"]
